# Generated by Django 5.1.1 on 2024-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='decription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
