# Generated by Django 5.1.1 on 2024-09-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_name_category_cat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imange'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
