# Generated by Django 5.1.1 on 2024-09-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_profile_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
